"""run cost columns

Revision ID: 22b7a77a9541
Revises: 7f871a98bc4d
Create Date: 2026-07-30 15:04:52.548216

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "22b7a77a9541"
down_revision: Union[str, Sequence[str], None] = "7f871a98bc4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "research_runs",
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "research_runs",
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "research_runs",
        sa.Column("cost_usd", sa.Float(), nullable=False, server_default="0"),
    )
    op.alter_column("research_runs", "input_tokens", server_default=None)
    op.alter_column("research_runs", "output_tokens", server_default=None)
    op.alter_column("research_runs", "cost_usd", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("research_runs", "cost_usd")
    op.drop_column("research_runs", "output_tokens")
    op.drop_column("research_runs", "input_tokens")
    # ### end Alembic commands ###
