"""Deterministic PDF rendering of a completed research run."""

from datetime import UTC, datetime

from fpdf import FPDF

from financial_research_agent.agents.state import ResearchState
from financial_research_agent.logging_config import get_logger

log = get_logger(__name__)

_DISCLAIMER = (
    "Generated by an automated research system for educational purposes. "
    "Not investment advice."
)


def _latin1(text: str) -> str:
    """Coerce text to latin-1 (fpdf core-font charset)."""
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _fmt(value: float | None, suffix: str = "") -> str:
    return f"{value:.1f}{suffix}" if value is not None else "n/a"


class _Report(FPDF):
    def header(self) -> None:
        self.set_font("helvetica", "I", 8)
        self.set_text_color(130)
        self.cell(0, 6, "Autonomous Financial Research Agent", align="R")
        self.ln(10)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("helvetica", "I", 7)
        self.set_text_color(130)
        self.multi_cell(0, 4, _DISCLAIMER, align="C")

    def section(self, title: str) -> None:
        self.set_font("helvetica", "B", 13)
        self.set_text_color(0)
        self.ln(4)
        self.cell(0, 8, _latin1(title), new_x="LMARGIN", new_y="NEXT")

    def body(self, text: str, *, size: int = 10, indent: float = 0.0) -> None:
        self.set_font("helvetica", "", size)
        self.set_text_color(30)
        self.set_x(self.l_margin + indent)
        self.multi_cell(self.epw - indent, 5, _latin1(text))


def render_pdf(state: ResearchState) -> bytes:
    """Render the research state as a professional PDF report."""
    pdf = _Report()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_font("helvetica", "B", 20)
    pdf.cell(0, 12, _latin1(f"{state.ticker} — Research Report"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(100)
    pdf.cell(
        0,
        6,
        f"Generated {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )

    if state.summary:
        pdf.section("Executive Summary")
        pdf.set_font("helvetica", "B", 10)
        pdf.body(state.summary.headline, size=11)
        pdf.body(state.summary.thesis)
        pdf.body("Strengths: " + "; ".join(state.summary.strengths))
        pdf.body("Concerns: " + "; ".join(state.summary.concerns))

    if state.metrics:
        pdf.section("Key Metrics (deterministic)")
        pdf.set_font("helvetica", "B", 9)
        header = f"{'FY':<6}{'Revenue':>12}{'Growth':>9}{'Net margin':>12}{'ROE':>8}"
        pdf.body(header, size=9)
        for m in state.metrics.annual:
            rev = f"{m.revenue / 1e9:.1f}B" if m.revenue is not None else "n/a"
            row = (
                f"{m.fiscal_year:<6}{rev:>12}"
                f"{_fmt(m.revenue_growth_pct, '%'):>9}"
                f"{_fmt(m.net_margin_pct, '%'):>12}"
                f"{_fmt(m.roe_pct, '%'):>8}"
            )
            pdf.body(row, size=9)
        pdf.body(f"Revenue CAGR: {_fmt(state.metrics.revenue_cagr_pct, '%')}", size=9)

    for title, items in (("Risks", state.risks), ("Opportunities", state.opportunities)):
        if items:
            pdf.section(title)
            for item in items:
                pdf.set_font("helvetica", "B", 10)
                pdf.body(f"[{item.severity.upper()}] {item.title}")
                pdf.body(item.detail, indent=4)

    if state.filing_insights:
        pdf.section("Filing Insights (cited)")
        for ins in state.filing_insights:
            pdf.set_font("helvetica", "B", 10)
            pdf.body(f"[{ins.severity.upper()}] {ins.title}")
            pdf.body(ins.detail, indent=4)
            for ref in ins.evidence:
                pdf.body(
                    f'Source {ref.form_type} {ref.filing_date}: "{ref.excerpt}..."',
                    size=8,
                    indent=8,
                )

    if state.errors:
        pdf.section("Data Gaps")
        for err in state.errors:
            pdf.body(f"{err.node}: {err.message}", size=8)

    data = bytes(pdf.output())
    log.info("pdf_rendered", bytes=len(data))
    return data